spring:
  jpa:
    properties:
      hibernate:
        default_schema: public

  liquibase:
    enabled: true
    change-log: db/changelog/master.yaml

  docker:
    compose:
      file: src/main/docker/compose.yaml
      enabled: true
      lifecycle-management: start_only

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/keycloak_springboot
          jwk-set-uri: http://localhost:8080/realms/keycloak_springboot/protocol/openid-connect/certs

logging:
  level:
    org.springframework.security: DEBUG
    org.keycloak: DEBUG
    org.youcode.hunters_leagues: DEBUG

server:
  port: 8443
  ssl:
    key-store: classpath:keystore.p12
    key-store-password: password
    key-store-type: PKCS12
    key-alias: mycert
keycloak:
  auth-server-url: http://localhost:8080
  realm: keycloak_springboot
  resource: hunterleague
  credentials:
    secret: Eg1co8UZp1K74pSfC94IMR9c8yM594dM
  admin:
    client-id: admin-cli
    client-secret: UO35XLxd0XhUaDOnCSQn6DUE73WSa7SK